participants:

  left:
    name: Oskar
    country: Peru
    language: spanska
    position:
      x: 0.7
      y: 0.0
      z: 2.0

  right:
    name: Joan
    country: Brasilien
    language: portugisiska
    position:
      x: -0.7
      y: 0.0
      z: 2.0

  condition: personal

file_storage:
  service_name: 'werewolf'
  host: '192.168.0.103'
  port: 139

logging:
  log_path: '/Users/jdlopes/Sprakkafe/logs'

messaging:
  broker_host: "ctt81.csc.kth.se"
  broker_port: 5672
  broker_user: "guest"
  broker_pass: "guest"

  # time server host
  time_server_host: "tcp://130.237.67.10:45321"

  # connection server
  connection_server_host: "tcp://CONNECTION SERVER IP ADDRESS:45322"

  # sensor hosts
  mocap_host: "MOCAP IP ADDRESS"

  # exchanges
  artificial_agent: "artificial-agent"
  sensors: "sensors"
  pre_processing: "pre-processor"
  environment: "environment"
  wizard: "wizard"
  fatima: "fatima"
  dialogue: "agent"

  # sensors
  microphone: "microphone"
  camera: "camera"
  kinect: "kinect"
  mocap: "mocap"
  tobii: "tobii"

  # new sensor
  new_sensor_mocap: "mocap.new_sensor.all"
  new_sensor_tobii: "tobii.new_sensor"

  # pre_processing
  mocap_processing: "mocap.processing"
  tobii_processing: "tobii.processing"
  openface: "openface"

  #processors
  mocaptobii_processing: "mocaptobii.processing"
  position_data: "position.data"
  asr_watson: "asr.data"
  dialogue_acts : "dialogue_act.data"
